# Rust formatting rules
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Max"
reorder_imports = true
normalize_doc_attributes = true
combine_control_expr = true
wrap_comments = true
format_code_in_doc_comments = true
